dist: trusty
sudo: required
language: node_js
node_js:
  - node
os:
  - linux
jobs:
  include:
    - stage: install
      script:
        - yarn install
      skip_cleanup: true
    - stage: build
      script:
        - travis_wait 30 yarn build:prod
      skip_cleanup: true
    - stage: release
      script:
        - yarn release:ci
      if: branch = master
      skip_cleanup: true
    - stage: deploy
      script:
        -  travis_wait 30 yarn deploy